name: holborn-prelude
version: 0.1.0.0
synopsis: Standard prelude for Holborn
license: AllRightsReserved

ghc-options: -Wall -Werror
default-extensions:
  - GeneralizedNewtypeDeriving
  - MonadFailDesugaring
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables

dependencies:
  - base >=4.9 && <5
  - hashable
  - mtl
  - protolude >= 0.1.6
  - safe >= 0.3.9
  - text >= 1.2.2

library:
  source-dirs: lib
  exposed-modules:
    - HolbornPrelude

tests:
  holborn-prelude-tests:
    main: Tests.hs
    source-dirs: tests
    ghc-options: -eventlog
    dependencies:
      - holborn-prelude
      - tasty >= 0.11
      - tasty-hspec >= 1.1.3
      - tasty-hunit >= 0.9.2
      - tasty-quickcheck >= 0.8.4
