name: holborn-api
version: 0.1.0.0
synopsis: API server for Holborn
license: AllRightsReserved

data-files:
  - sql/initial.sql

ghc-options: -Wall -Werror
default-extensions:
  - GeneralizedNewtypeDeriving
  - MonadFailDesugaring
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - ScopedTypeVariables
  - RecordWildCards

dependencies:
  - base >=4.9 && <5
  - holborn-common-types
  - holborn-prelude

library:
  source-dirs: lib
  dependencies:
    - aeson >= 0.10
    - bytestring
    - errors
    - exceptions >= 0.8
    - http-api-data
    - http-client
    - http-types
    - postgresql-simple
    - servant-docs >= 0.5
    - servant-server
    - text
    - time
    - transformers
    - wai
    # We literally depend on this only for Port
    - warp >= 3.1

executables:
  holborn-api-server:
    main: Main.hs
    source-dirs: holborn-api-server
    dependencies:
      - holborn-api
      - optparse-applicative
      - wai-cors
      - wai-extra
      - warp >= 3.1
      - postgresql-simple

  gen-purescript:
    main: Main.hs
    source-dirs: gen-purescript
    dependencies:
      - holborn-api
      - purescript-bridge
      - servant-purescript


tests:
  holborn-api-tests:
    main: Main.hs
    source-dirs: tests
    ghc-options: -eventlog
    dependencies:
      - QuickCheck
      - aeson
      - bytestring
      - containers
      - errors
      - http-api-data
      - holborn-api
      - hspec-wai >= 0.6.5
      - hspec-wai-json >= 0.6.0
      - http-client
      - http-types
      - postgresql-simple
      - process
      - tasty >= 0.10
      - tasty-hspec >= 1.1.0
      - tasty-hunit >= 0.9.0
      - tasty-quickcheck >= 0.8
      - text
      - transformers
      - unix
      - wai
      - wai-extra
