name: hcl
version: 0.1.0.0
synopsis: Command line tool for Holborn
license: AGPL
license-file: LICENSE
copyright: (c) 2015-2017 Thomas E. Hunger and Jonathan M. Lange

ghc-options: -Wall -Werror -threaded
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - NamedFieldPuns
  - MonadFailDesugaring
source-dirs: src

dependencies:
  - base >=4.9 && <5
  - holborn-prelude

executables:
  hcl-wait-for-port:
    main: wait-for-port.hs
    dependencies:
      - optparse-applicative
      - network-simple >= 0.4

  hcl-unused:
    main: unused.hs
    dependencies:
      - turtle
