name: holborn-syntax
version: 0.3.0.0
synopsis: Syntax analysis library
license: AGPL
license-file: LICENSE
copyright: (c) 2015-2017 Thomas E. Hunger and Jonathan M. Lange

# Temporarily disable -Werror while we migrate to Protolude
ghc-options: -Wall
default-extensions:
  - GeneralizedNewtypeDeriving
  - MonadFailDesugaring
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards

dependencies:
  - base >= 4.9 && < 5.0
  - holborn-prelude
  - text

library:
  source-dirs: lib
  dependencies:
    - bytestring >= 0.10
    - containers >= 0.5
    - errors >= 2.0
    - highlighter2 >= 0.2
    - language-python >= 0.5.2
    - mtl >= 2.2
    - pretty-error

tests:
  holborn-syntax-test:
    main: Tests.hs
    source-dirs: tests
    dependencies:
      - holborn-syntax
      - tasty
      - tasty-hunit
      - tasty-quickcheck

