# A box running all the components of Buildbot
{ config, pkgs, lib, ... }:
let
  workerPort = 9989;
  # PUPPY: Re-using credentials from deploy box.
  gitRepo = "https://holbornlondon:DSmiB2AVZJhftk4XRyH1N98XNMYzOmY9@bitbucket.org/holbornlondon/holborn";
  gitBranch = "master";
  builderName = "holborn-experimental-builder";
  projectName = "holborn";
  projectURL = "https://bitbucket.com/holbornlondon/holborn";
  buildbotWebPort = 3000;
  # XXX: Duplicated somewhat from the AWS deployment file:
  # XXX: Port is from oauth2_proxy's httpAddress
  # TODO: Put this behind nginx so we can stop worrying about ports.
  buildbotURL = "http://buildbot.mumak.net:4180/";
  pollInterval = 300; # poll git repo every N seconds
  workerName = "single-host";
  # PUPPY: We don't really care what this is as long as master & worker are
  # synchronized.
  #
  # Secret randomly generated by Lastpass.
  workerPassword = "1HsPjuU9HvPRDVH58fNm3Sevy6666MILNDKh1O7V6jrUFxnL3v7Hb4EI93m3ax6o";

in
{
  require = [
    ../modules/buildbot-master.nix
    ../modules/buildbot-worker.nix
    ../modules/oauth2_proxy.nix
  ];

  environment.systemPackages = [];

  # If the master doesn't come up properly then the worker will give up trying
  # to connect and need a kick in the pants.
  services.buildbot-worker = {
    enable = true;
    name = workerName;
    password  = workerPassword;
    adminContact = "Jonathan Lange <jml@mumak.net>";
    hostInfo = "Worker running on same box as master.";
    buildmasterHost = "localhost";
    buildmasterPort = workerPort;
    # We need git to be able to get the source code to build it!
    extraPackages = [ pkgs.git ];
  };

  # TODO: Only bind web service to loopback device.
  services.buildbot = {
    enable = true;
    configFile = pkgs.writeText "master.cfg" (import ./templates/master.cfg.nix
    { inherit projectName projectURL workerPort buildbotURL buildbotWebPort;
      inherit gitRepo gitBranch builderName pollInterval workerName workerPassword;
    });
    # We need git to be able to poll for changes.
    extraPackages = [ pkgs.git ];
  };

  services.oauth2_proxy = {
    enable = true;
    provider = "google";
    clientID = "579594549675-nuh9d5m5kvdckfdec785o9cbcqe6sje7.apps.googleusercontent.com";
    # PUPPY: Shared secret.
    clientSecret = "bLlMleNsy_63ivGSIktA1EpP";
    cookie = {
      refresh = "1h";
      # XXX: jml doesn't actually understand what this is for.
      # PUPPY: Shared secret.
      # Randomly generated w/ Lastpass.
      secret = "dC1AKxDIlcDzmJOIUh0P1HG7CfoMke4u";
      secure = false;
    };
    httpAddress = "http://0.0.0.0:4180";
    # oauth2_proxy *almost* guesses right. It insists on 'https' though, which
    # isn't being served (yet!) or configured as a valid redirect URL at
    # Google's side.
    redirectURL = "http://buildbot.mumak.net:4180/oauth2/callback";
    upstream = "http://localhost:3000";
    email.addresses = ''
      jonathan.lange@gmail.com
      thomas.e.hunger@gmail.com
    '';
  };

  services.sshd.enable = true;
  # XXX: '4180' duplicated from httpAddress
  # XXX: After we bind buildbot web service to loopback, remove buildbotWebPort from this list.
  networking.firewall.allowedTCPPorts = [ 22 80 443 4180 ];
}
